### ISSUE TITLE
Can't run even a simple example.

### ISSUE THREAD

**Issue by MasterGroosha** [luckydonald/pytg#105]
### The problem
Hi there! I have a problem with pyth since yet a simpliest example from README doesn't work for me.

### Your environment
pytg 0.4.10, Python 3.5, OS: Ubuntu 16.04 running on ODroid-C1

### Steps to reproduce
The code is:  
```python
# -*- coding: utf-8 -*-
from pytg import Telegram
tg = Telegram(
    telegram="/telegram/tg/bin/telegram-cli", # path is correct!
    pubkey_file="/telegram/tg/tg-server.pub")
receiver = tg.receiver
sender = tg.sender
sender.send_msg("my_username_or_id_tried_both", "Hello World!")
```

And error outputs after **2** runs in a row (one after another to compare errors) are:
```
root@odroid:/telegram# python3.5 testbot1/bot.py
change_user_group: can't find the user telegramd to switch to
Traceback (most recent call last):
  File "testbot1/bot.py", line 10, in <module>
    sender.send_msg("MY_ID_WAS_HERE", "Hello World!")
  File "/usr/local/lib/python3.5/dist-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pytg/sender.py", line 354, in execute_function
    raise e
  File "/usr/local/lib/python3.5/dist-packages/pytg/sender.py", line 351, in execute_function
    return result_parser(message)
  File "/usr/local/lib/python3.5/dist-packages/pytg/result_parser.py", line 55, in success_fail
    raise FailException(json.error_code, json.error)
pytg.exceptions.FailException: Error 38: 'can not parse arg #1' (command "[disable_preview] msg MY_ID_WAS_HERE 'Hello World!'\n")
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1700, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
read: Connection reset by peer
root@odroid:/telegram# python3.5 testbot1/bot.py
change_user_group: can't find the user telegramd to switch to
bind: Address already in use
Traceback (most recent call last):
  File "testbot1/bot.py", line 10, in <module>
    sender.send_msg("MY_ID_WAS_HERE", "Hello World!")
  File "/usr/local/lib/python3.5/dist-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pytg/sender.py", line 354, in execute_function
    raise e
  File "/usr/local/lib/python3.5/dist-packages/pytg/sender.py", line 351, in execute_function
    return result_parser(message)
  File "/usr/local/lib/python3.5/dist-packages/pytg/result_parser.py", line 55, in success_fail
    raise FailException(json.error_code, json.error)
pytg.exceptions.FailException: Error 38: 'can not parse arg #1' (command "[disable_preview] msg MY_ID_WAS_HERE 'Hello World!'\n")
```

Here's also DEBUG log:
```

root@odroid:/telegram# python3.5 testbot1/bot.py
INFO:pytg:Starting Telegram Executable: "/telegram/tg/bin/telegram-cli -R -W -P 4458 -k /telegram/tg/tg-server.pub --json --permanent-peer-ids --permanent-peer-ids"
DEBUG:pytg.sender:Parsing raw: Argument help - <command> (needed)
DEBUG:pytg.sender:Sending command >[disable_preview]  help
<
INFO:pytg:CLI did not responde.
change_user_group: can't find the user telegramd to switch to
DEBUG:pytg.sender:Parsing raw: Argument help - <command> (needed)
DEBUG:pytg.sender:Sending command >[disable_preview]  help
<
DEBUG:pytg.sender:Socket Connected.
DEBUG:pytg.sender:All Sent.
INFO:pytg:CLI available.
DEBUG:pytg.sender:Parsing send_msg: Argument MY_ID_HERE - <peer> (needed)
DEBUG:pytg.sender:Parsing send_msg: Argument Hello World! - <text> (needed)
DEBUG:pytg.sender:Sending command >[disable_preview] msg MY_ID_HERE 'Hello World!'
<
DEBUG:pytg.sender:Socket Connected.
DEBUG:pytg.sender:All Sent.
Traceback (most recent call last):
  File "testbot1/bot.py", line 13, in <module>
    sender.send_msg("MY_ID_HERE", "Hello World!")
  File "/usr/local/lib/python3.5/dist-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pytg/sender.py", line 354, in execute_function
    raise e
  File "/usr/local/lib/python3.5/dist-packages/pytg/sender.py", line 351, in execute_function
    return result_parser(message)
  File "/usr/local/lib/python3.5/dist-packages/pytg/result_parser.py", line 55, in success_fail
    raise FailException(json.error_code, json.error)
pytg.exceptions.FailException: Error 38: 'can not parse arg #1' (command "[disable_preview] msg MY_ID_HERE 'Hello World!'\n")
INFO:pytg.sender:Quit Sending. Not allowing sending anymore.
WARNING:pytg.sender:Terminating currently sending request.
INFO:pytg.sender:Currently not Sending.
INFO:pytg:Closing Connections.
DEBUG:pytg:Closing sender.
DEBUG:pytg.sender:Already did quit Sending. Not allowing sending.
WARNING:pytg.sender:Terminating currently sending request.
INFO:pytg.sender:Currently not Sending.
DEBUG:pytg:Closing sender.
DEBUG:pytg.receiver:receiver thread existing: Not created.
INFO:pytg:Asking to CLI to stop.
DEBUG:pytg:Sender already stopped. Unable to issue safe_quit or quit to exit via socket.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1700, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
read: Connection reset by peer
```

### Expected behaviour
A message should be sent to chat with my another account

### Actual behaviour
Error happens!

**Comment by luckydonald** [comment]
`Error 38: 'can not parse arg #1'`  indicates that `MY_ID_WAS_HERE` was wrong in some way.

Best to start the CLI yourself (The debug output indicated `/telegram/tg/bin/telegram-cli -R -W -P 4458 -k /telegram/tg/tg-server.pub --json --permanent-peer-ids --permanent-peer-ids`) and try yourself how what argument you need.
After that failed, it is shutting down (everything after `INFO:pytg.sender:Quit Sending. Not allowing sending anymore.`) because your script is done.

**Comment by luckydonald** [comment]
As for the argument you can try `@my_username`, `userid#1234`, `user#1234`

**Comment by MasterGroosha** [comment]
Well, after running cli beforehand, script started working, thanks!

**Comment by luckydonald** [comment]
`change_user_group: can't find the user telegramd to switch to` #81
