### ISSUE TITLE
contacts_list does not work

### ISSUE THREAD

**Issue by vonabarak** [luckydonald/pytg#36]
Exception raises when i try to get list of contacts:
```python
sender.contacts_list()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/vonabarak/tgsrv/lib/python3.4/site-packages/pytg-0.4.1rc0-py3.4.egg/pytg/sender.py", line 548, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/home/vonabarak/tgsrv/lib/python3.4/site-packages/pytg-0.4.1rc0-py3.4.egg/pytg/sender.py", line 275, in execute_function
    return result_parser(message)
  File "/home/vonabarak/tgsrv/lib/python3.4/site-packages/pytg-0.4.1rc0-py3.4.egg/pytg/result_parser.py", line 30, in success_fail
    if json.result == u("SUCCESS"):
AttributeError: 'DictObjectList' object has no attribute 'result'
```

Probably it should have res.List() instead of res.success_fail in sender.py line 104

**Comment by Stepkaa** [comment]
I get exactly the same error since yesteray.

**Comment by luckydonald** [comment]
Can you give me a log of that? 
Just put that at the begin of your code:
```python
import logging ; logging.basicConfig(level=logging.DEBUG)  # enable debug output
```

**Comment by vonabarak** [comment]
Sure. Here is log/
Python 3.4.1 (default, Jul  3 2015, 23:56:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytg
>>> from pytg.receiver import Receiver # get messages
>>> from pytg.sender import Sender # send messages, and other querys.
>>> from pytg.utils import coroutine
>>> sender = Sender(host="localhost", port=4458)
>>> import logging ; logging.basicConfig(level=logging.DEBUG)
>>> sender.contacts_list()
DEBUG:pytg.sender:Sending command > [disable_preview] contact_list 
<
DEBUG:pytg.sender:Socket Connected.
DEBUG:pytg.sender:All Sent.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vonabarak/pytg/lib/python3.4/site-packages/pytg-0.4.1rc0-py3.4.egg/pytg/sender.py", line 548, in command_alias
  File "/home/vonabarak/pytg/lib/python3.4/site-packages/pytg-0.4.1rc0-py3.4.egg/pytg/sender.py", line 275, in execute_function
  File "/home/vonabarak/pytg/lib/python3.4/site-packages/pytg-0.4.1rc0-py3.4.egg/pytg/result_parser.py", line 30, in success_fail
AttributeError: 'DictObjectList' object has no attribute 'result'
>>>

**Comment by farzadab** [comment]
i had the same issue, i did fix it like this but i don't know if that's good.
not all the responses have a "result" attribute (as i've seen, not a lot of them do), so in pytg/result_parser.py, in function success_fail in the first line (before the two if's) i added:
if not hasattr(json, 'result'):
  return json


also i added another change, for the contact_add function, when it gets to function something in the same file (result_parser.py) because the length is equal to one, an exception is thrown, i changed the line 22 as follows:
-       if not (value and len(value) > 1):
+       if not (value and len(value) >= 1):

**Comment by luckydonald** [comment]
#37 fixed that.
