### ISSUE TITLE
IllegalResponseException instead of NoResponse

### ISSUE THREAD

**Issue by Zonker96** [luckydonald/pytg#50]
**Your basic code with my code**

```
from pytg.utils import coroutine
from pytg.sender import Sender
from pytg.receiver import Receiver
receiver = Receiver(host="localhost", port=4458)
sender = Sender(host="localhost", port=4458)


@coroutine # from pytg.utils import coroutine
def main_loop():
    while not QUIT:
        msg = (yield) # it waits until it got a message, stored now in msg.
        print("Message: ", msg.text)
        # do more stuff here!

sender.send_msg("Patrick", "Hallo")

receiver.start()
receiver.message(main_loop())
```

**The Error's**

```
Result parser does not allow exceptions, but we got one:
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/pytg-0.4.1d-py3.2.egg/pytg/sender.py", line 426, in _do_send
    answer = self.s.recv(1)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/pytg-0.4.1d-py3.2.egg/pytg/sender.py", line 250, in execute_function
    result = self._do_command(command_name, new_args, answer_timeout=result_timeout, retry_connect=retry_connect, enable_preview=enable_preview, reply_id=reply_id)
  File "/usr/local/lib/python3.2/dist-packages/pytg-0.4.1d-py3.2.egg/pytg/sender.py", line 359, in _do_command
    result = self._do_send(request, answer_timeout=answer_timeout, retry_connect=retry_connect)
  File "/usr/local/lib/python3.2/dist-packages/pytg-0.4.1d-py3.2.egg/pytg/sender.py", line 449, in _do_send
    raise NoResponse(command)
pytg.exceptions.NoResponse:  [disable_preview] msg Patrick 'Hallo'

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/pytg-0.4.1d-py3.2.egg/pytg/sender.py", line 426, in _do_send
    answer = self.s.recv(1)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/pytg-0.4.1d-py3.2.egg/pytg/sender.py", line 250, in execute_function
    result = self._do_command(command_name, new_args, answer_timeout=result_timeout, retry_connect=retry_connect, enable_preview=enable_preview, reply_id=reply_id)
  File "/usr/local/lib/python3.2/dist-packages/pytg-0.4.1d-py3.2.egg/pytg/sender.py", line 359, in _do_command
    result = self._do_send(request, answer_timeout=answer_timeout, retry_connect=retry_connect)
  File "/usr/local/lib/python3.2/dist-packages/pytg-0.4.1d-py3.2.egg/pytg/sender.py", line 449, in _do_send
    raise NoResponse(command)
pytg.exceptions.NoResponse:  [disable_preview] msg Patrick 'Hallo'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 15, in <module>
    sender.send_msg("Patrick", "Hallo")
  File "/usr/local/lib/python3.2/dist-packages/pytg-0.4.1d-py3.2.egg/pytg/sender.py", line 548, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/pytg-0.4.1d-py3.2.egg/pytg/sender.py", line 259, in execute_function
    raise IllegalResponseException("Result parser does not allow exceptions.")
pytg.exceptions.IllegalResponseException: Result parser does not allow exceptions.
Terminating currently sending request.
```

I Started the Client and he dosent give me a error. I will try to find the Error by the client.. Mybe you know what I am doing wrong ... (Using Python3.2)

**Comment by luckydonald** [comment]
```pytg.exceptions.NoResponse```
Sometimes the CLI doesn't answer.
I have not seen why or when that happens and when/why not.
But it shouldn't throw a ```pytg.exceptions.IllegalResponseException```, indeed.

**Comment by luckydonald** [comment]
The commit f745d92cce23f4c965a420b0736be7e4201395a8 should have solved that.
