### ISSUE TITLE
sender.contacts_search() has invalid parser.

### ISSUE THREAD

**Issue by gregvirgin** [luckydonald/pytg#51]
Doesn't matter what I put into it, queries that work in telegram-cli don't work at all here.
```
>>> sender.contacts_search("luckydonald")
DEBUG:pytg.sender:Parsing contacts_search: Argument luckydonald - <user_name> (needed)
DEBUG:pytg.sender:Skipping missing optional parameter #1 [limit] (type NonNegativeNumber) in function contacts_search.
DEBUG:pytg.sender:Sending command > [disable_preview] contact_search 'luckydonald'
<
DEBUG:pytg.sender:Socket Connected.
DEBUG:pytg.sender:All Sent.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/DictObject/__init__.py", line 435, in __getattr__
    value = dict.__getattribute__(self, n(name))  # Raise exception if not found in original dict's attributes either
AttributeError: 'DictObject' object has no attribute 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/DictObject/__init__.py", line 442, in __getattr__
    key_name = self._attribute_to_key_map[n(name)]  # Check if we have this set.
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 548, in command_alias
  File "/usr/local/lib/python3.4/dist-packages/pytg-0.4.1d-py3.4.egg/pytg/sender.py", line 275, in execute_function
  File "/usr/local/lib/python3.4/dist-packages/pytg-0.4.1d-py3.4.egg/pytg/result_parser.py", line 30, in success_fail
  File "/usr/local/lib/python3.4/dist-packages/DictObject/__init__.py", line 456, in __getattr__
    raise suppress_context(AttributeError(name))
AttributeError: result
```

**Comment by luckydonald** [comment]
Can you please post the output in the telegram cli, when you start it with the ```--json``` flag?

**Comment by luckydonald** [comment]
```[disable_preview] contact_search 'luckydonald'```
```json
{"id": 1234, "type": "user", "print_name": "luckydonald", "flags": 259, "first_name": "luckydonald", "last_name": "", "phone": "1234", "username": "luckydonald"}
```

**Comment by luckydonald** [comment]
Okey, needs some parser.

**Comment by luckydonald** [comment]
For now the ```something``` parser is working.
