### ISSUE TITLE
pip doesn't seem to pick up the luckydonald-utils dependency

### ISSUE THREAD

**Issue by dequis** [luckydonald/pytg#55]
I know i could just install it but i'd expect it to just work™

```
$ sudo pip install pytg
[sudo] password for dx:
Collecting pytg
  Downloading pytg-0.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-73hkqbzs/pytg/setup.py", line 8, in <module>
        from pytg import VERSION
      File "/tmp/pip-build-73hkqbzs/pytg/pytg/__init__.py", line 9, in <module>
        from luckydonaldUtils.encoding import to_unicode as u
    ImportError: No module named 'luckydonaldUtils'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-73hkqbzs/pytg
```

```
$ pip --version
pip 7.1.2 from /usr/lib/python3.5/site-packages (python 3.5)
$ pip list | grep setuptools
setuptools (18.5)
```

**Comment by luckydonald** [comment]
Quick solution, until I got the dependencies in correct order:
```pip install luckydonald-utils```

**Comment by luckydonald** [comment]
should be fixed in v0.4.3 now.

**Comment by dequis** [comment]
>Successfully installed DictObject-0.1.2 luckydonald-utils-0.33 pytg-0.4.4

Looks good now. Thanks!

**Comment by luckydonald** [comment]
Awesome.
