### ISSUE TITLE
Permission denied in running cli

### ISSUE THREAD

**Issue by vhdmsm** [luckydonald/pytg#62]
When i try to run my ```dumper.py``` as a periodic task that calls telegram-cli rather than running cli in background manually(test branch is not stable and will crash) , i get ```open[config_file]: Permission denied``` error when pytg tries to run cli:
```
[2016-02-14 19:13:02,692: DEBUG/MainProcess] Task accepted: tasks.run_dumper[fd4bad84-f3d8-4383-b098-3636f62649fe] pid:3788
[2016-02-14 19:13:02,699: INFO/Worker-2] Starting Telegram Executable: "/home/telegramd/tgchannel/tg/bin/telegram-cli -R -W -P 4458 -k /home/telegramd/tgchannel/tg/server.pub --json"
[2016-02-14 19:13:02,703: DEBUG/Worker-2] Parsing raw: Argument help - <command> (needed)
[2016-02-14 19:13:02,704: DEBUG/Worker-2] Sending command > [disable_preview]  help
<
open[config_file]: Permission denied
[2016-02-14 19:13:02,709: INFO/Worker-2] CLI did not responde.
[2016-02-14 19:13:03,710: DEBUG/Worker-2] Parsing raw: Argument help - <command> (needed)
[2016-02-14 19:13:03,711: DEBUG/Worker-2] Sending command > [disable_preview]  help
<
[2016-02-14 19:13:03,711: INFO/Worker-2] CLI did not responde.
[2016-02-14 19:13:04,716: ERROR/MainProcess] Task tasks.run_dumper[fd4bad84-f3d8-4383-b098-3636f62649fe] raised unexpected: AssertionError('CLI Process died.',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/telegramd/telegram_dumper/tasks.py", line 13, in run_dumper
    main()
  File "/home/telegramd/telegram_dumper/dumper.py", line 170, in main
    pubkey_file="/home/telegramd/tgchannel/tg/server.pub")
  File "/usr/local/lib/python3.4/site-packages/pytg-0.4.5-py3.4.egg/pytg/__init__.py", line 50, in __init__
AssertionError: CLI Process died.
```
P.S: i'm running pytg as daemon in supervisord.

**Comment by luckydonald** [comment]
I am not quite sure about your setup, did you turn on all the logging in pytg?

Some basic things would to check the path, and the actual permission of the cli (does it fit with your supervisord configuration?) 

As I never have used supervisord, I can not help you if it is specifically related to that, sorry.

**Comment by luckydonald** [comment]
In fact, `open[config_file]: Permission denied` is not coming from pytg. So I assume it is the CLI itself.
Try what happens if you enter the same command as built by the cli [found in the log, with level INFO](https://github.com/luckydonald/pytg/blob/33bcad029a3bc3f3daa406d50a50bdeffc638e1a/pytg/__init__.py#L78).

**Comment by vhdmsm** [comment]
Well it was a problem in configuration and communicating with cli, Fixed.

**Comment by luckydonald** [comment]
If you think your solution could help others, feel free to tell us more details.

**Comment by vhdmsm** [comment]
Yes, i'll do it later. i'm rly busy for a while.

**Comment by luckydonald** [comment]
Might be related with #81, too.

**Comment by gictor** [comment]
> Yes, i'll do it later. i'm rly busy for a while.

still busy?
