### ISSUE TITLE
Exception 'file is not a type File' or 'file path x not valid' while using send_file

### ISSUE THREAD

**Issue by a3dho3yn** [luckydonald/pytg#67]
### The problem
In telegram-cli, I can send file by following command:
```
> send_file TheContact 'path/to/file'
```
but using pytg, I will get exception if I pass file path string or File('path/to'file') to send_file method.

### Environment
python 2.7.11 on Windows
telegram-cli on Manjaro

### Steps to reproduce
Run telegram-cli on json mode and on desired port
Try to send file to a contact using Sender

Detailed steps to reproduce the issue.
```
from pytg.sender import Sender
sender = Sender(host, port)
sender.send_file(u'TheContact', File('path/to/file.png'))
```
or
```
sender.send_file(u'TheContact', 'assets/test.png'))
```

### Expected behaviour
Send specified file to the contact.

### Actual behaviour
On first case, It raises 'file path x not valid' and on the second case it raises 'is not a type File'

I guess the problem is File parses path to <path> format. which will return False in path.isfile

**Comment by luckydonald** [comment]
Can you post the full stacktrace, please?
I believe it is about windows having paths like `C:\path\to\file` instead of `/path/to/file`.
I am also confused that your CLI is running on a Linux, but your python is running on Microsoft Windows?

**Comment by a3dho3yn** [comment]
You're right about windows paths format (and also absolute paths), but the result of path.isfile for relative paths like 'assets/fonts/arial.ttf' is True (on Windows)

Yes, telegram-cli is running on a VM and is accessible via TCP port from Windows.
I started telegram-cli using this parameters:
```
> bin/telegram-cli -k tg-server.pub --json -p 9999 -W --accept-any-tcp
```

I don't have access to my desktop till tomorrow (to send you stack traces).
But I guessed the issue is with hosting the file on a different machine than telegram-cli is running.
So I tested a sample code in python on the same machine which telegram-cli is running, and it works fine! I don't know whether path format was the issue or hosting file on a different machine.
I will also try absolute paths on windows tomorrow.

**Comment by a3dho3yn** [comment]
I think there are two (or may be three) issues, one with my setup and one (or two) with the send_file method.
My setup issue is hosting file on a different machine than telegram-cli.
Issue of send_file is that the path should be presented as absolute (or relative to the telegram-cli directory)

I checked two cases on the same machine which telegram-cli was running:
```sender.send_file('Hossein_Taleghani', 'assets/sign.png')```
which issued:
```{'error': 'Can not open file: No such file or directory', 'error_code': 9, 'result': 'FAIL'}```

Then I checked:
```sender.send_file('Hossein_Taleghani', path.abspath('assets/sign.png'))```
which worked fine.

I think the solution for this issue is checking absolute path within send_file method (You can consider this as an improvement)

At last I checked the working code on Windows, It issued:
```
Traceback (most recent call last):
  File "test.py", line 72, in <module>
    sender.send_file('Hossein_Taleghani', path.abspath('assets/sign.png'))
  File "C:\Python27\lib\site-packages\pytg\sender.py", line 570, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "C:\Python27\lib\site-packages\pytg\sender.py", line 250, in execute_function
    command_name, new_args = self._validate_input(function_name, arguments)
  File "C:\Python27\lib\site-packages\pytg\sender.py", line 355, in _validate_input
    function_name=function_name, number=i, type=func_type.__class__.__name__, param=str(func_type), error=str(err)))
ValueError: Error in function send_file: parameter #1 <file> is not type File. (Not a string.)
```

then I checked:
```sender.send_file('Hossein_Taleghani', File('assets/sign.png'))```

which issued:
```
Traceback (most recent call last):
  File "test.py", line 72, in <module>
    sender.send_file(u'Hossein_Taleghani', File(path.abspath('assets/sign.png')))
  File "C:\Python27\lib\site-packages\pytg\sender.py", line 570, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "C:\Python27\lib\site-packages\pytg\sender.py", line 250, in execute_function
    command_name, new_args = self._validate_input(function_name, arguments)
  File "C:\Python27\lib\site-packages\pytg\sender.py", line 355, in _validate_input
    function_name=function_name, number=i, type=func_type.__class__.__name__, param=str(func_type), error=str(err)))
ValueError: Error in function send_file: parameter #1 <file> is not type File. (File path "<D:\tim_python\assets\sign.png>" not valid.)
```

I don't know why File adds <> to path string and I can't figure out these two exceptions.

For hosting file on a different machine, I suggest sending file content to telegram instead of sending file's path (If telegram-cli supports this). something like: ```send_file('Contact', open('path/to/file', 'rb'))```

**Comment by luckydonald** [comment]
##### No. 1:

This is the CLI complaining about not finding the file. 
It needs to be relative to the cli.
But then [pytg's check](https://github.com/luckydonald/pytg/blob/187aedbd4e5175aa00e1817430459328e46aeba0/pytg/argument_types.py#L180-L181) would fail, as this new path is not valid for pytg's current working directory)
Have this unneeded example:
```python
assets/sign.png
```
```python
/path/to/script/assets/sign.png
          ≠
/path/to/telegram/assets/sign.png
```
**Edit**: You already found that out.
Anyway, to resolve relative paths, I'd need to resolve them from the cli's dir. But that path is unknown to pytg.

##### No. 2:

Because the absolute path is valid for both pytg and tg.
[`os.path.abspath` documentation](https://docs.python.org/2/library/os.path.html#os.path.abspath)

##### No. 3:
```python
path.abspath('assets/sign.png')
```
is not a string in windows?
*Strange...*

What does 
```python
foo = path.abspath('assets/sign.png');
print(foo)
print(type(foo))
```
results in?
The functions, as you already figured out, are currently written to be used locally, and they pre-checks commonly made errors.

This could indeed need a way to disable that check...

##### No. 4:
>I don't know why File adds <> to path string

Can you check the output of 
```python
print(File('assets/sign.png'))
```
**Edit**: Oh!
You are using [`argument_types.File`](https://github.com/luckydonald/pytg/blob/187aedbd4e5175aa00e1817430459328e46aeba0/pytg/argument_types.py#L176-L183)
It is just a parser to check if the given argument is valid.
You shouldn't use this. A normal string should be fine.
The `<` `>` are just the [string representation](https://github.com/luckydonald/pytg/blob/187aedbd4e5175aa00e1817430459328e46aeba0/pytg/argument_types.py#L34) of an required argument (part of the automatic [help](https://github.com/luckydonald/pytg/tree/fcae46f950956d52d76c9fd7882acc5227095ec6#documentation) generation).
(commit 8d8b28d43a6db13650c0e9238757c4d0295993b8 renames it to `FilePath` to be more clear about it being not an actual file)


>  I suggest sending file content to telegram instead of sending file's path (If telegram-cli supports this)

This would be so great, but sadly the CLI doesn't support raw data input, it needs to read from a file path.

(The following observations of tg are from branch master, [commit 160231](https://github.com/vysheng/tg/tree/160231bdd7887316b544412e8b97bcdd86ac25a4))
Even the [Lua interface](https://github.com/vysheng/tg/blob/160231bdd7887316b544412e8b97bcdd86ac25a4/lua-tg.c#L1304-L1309) needs a path.

Digging deeper, in the deeps of tgl, [`tgl_do_send_document`](https://github.com/vysheng/tgl/blob/08b6340c1cbf1ef59690007b0207de9d5c904c07/queries.c#L1717)  will call [`_tgl_do_send_photo`](https://github.com/vysheng/tgl/blob/08b6340c1cbf1ef59690007b0207de9d5c904c07/queries.c#L1629). Either this function or the code in the called  [`send_part`](https://github.com/vysheng/tgl/blob/8b10d08732fd4fed2ff618426aeed5847dbe667e/queries.c#L1569) will only work with real files, as, for example, the total file size is required to be known.

**Comment by a3dho3yn** [comment]
The working code was tested on Python 3.4.3, but the similar code will fail on Python 2.7:
```
from os import path
from pytg.sender import Sender
sender = Sender('localhost', 9102)
sender.send_file(u'Hossein_Taleghani', path.abspath('assets/sign.png'))
```

**Traceback**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stet/tyt/.env/lib/python2.7/site-packages/pytg/sender.py", line 613, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/home/stet/tyt/.env/lib/python2.7/site-packages/pytg/sender.py", line 271, in execute_function
    command_name, new_args = self._validate_input(function_name, arguments)
  File "/home/stet/tyt/.env/lib/python2.7/site-packages/pytg/sender.py", line 397, in _validate_input
    function_name=function_name, number=i, type=func_type.__class__.__name__, param=str(func_type), error=str(err)))
ValueError: Error in function send_file: parameter #1 <file> is not type File. (Not a string.)
```

**Comment by luckydonald** [comment]
What does 
```python
foo = path.abspath('assets/sign.png');
print(foo)
print(type(foo))
```
results in?

**Comment by a3dho3yn** [comment]
Result on Python2.7 on windows
```
D:\@Me\Nozha\TYT\tim_python\assets\sign.png
<type 'str'>
```

**Comment by a3dho3yn** [comment]
The issue with python 2.7 happens on the linux machine (same machine as telegram-cli) not windows

**Comment by luckydonald** [comment]
Okey, it's probably because the path isn't `unicode`, but binary `str`.

**Comment by a3dho3yn** [comment]
I also tried path.abspath('assets/sign.png').format('utf-8'). Did not work.

**Comment by blitz79** [comment]
I tried doing this while using Python 2.7* on RPi and it works..:

````
path = /var/www/what/ever/path/it.is
path_utf = path.decode('utf-8')

sender.send_document(u"fname_lname", path_utf)
````
