### ISSUE TITLE
ASK> First Time on Initializing Telegram Account

### ISSUE THREAD

**Issue by drr3d** [luckydonald/pytg#73]
Hi there again Donald :+1: 

First, i'm sorry this is not really an issues, if you mind, i can move this post into another page(please give me a page to ask this question :smile: )

i still enjoying your works, thanks again.. :smile:

i have a some questions, regarding additional new account,

Whenever i try to initiate a new account/number/profile directly using Telegram-CLI, it always give some instruction, that require us to provide some information's, like phone number(usually after this Telegram would send us password to fill in Telegram-CLI), etc.

like the image below:
![pytg](https://cloud.githubusercontent.com/assets/6335497/13561364/d6352b62-e45e-11e5-95b5-d04ec80197d5.png)

is there any function that pytg can handle such task?

if no, is there a way i can do such task by modifying your module? without directly using Telegram-CLI?

sorry again for my bad English :smile:

Regards,
drr3d

**Comment by luckydonald** [comment]
Pytg is not yet capable of that.
However, I would welcome any solutions you get!

The start stuff of the CLI is in [`pytg/__init__.py:54`](https://github.com/luckydonald/pytg/blob/ed8d622a06fd24ec75c0c301984fa6d58ebd6e61/pytg/__init__.py#L54),
and stopping happens [in line `93`](https://github.com/luckydonald/pytg/blob/ed8d622a06fd24ec75c0c301984fa6d58ebd6e61/pytg/__init__.py#L93)
Especially stopping is a tricky part of code, as it should not leave a CLI running causing the port beeing blocked forever. (It took quite some time to get it right `:D`)

The reason why I did not implement yet, is mostly the detection of the input, (includes reading it), and the direct "typing the number" to the process. Checking for the code probably needs active polling, which is quite CPU intense.

**Comment by luckydonald** [comment]
Long time ago (before v0.3.0) this was exactly what pytg did, to get any messages.

Probably you should make the check optional, and stop polling (or restart?) after it verified the CLI is working correctly.

**Comment by drr3d** [comment]
Hi Donald

thx for your explanation, ok then i'll try to make it work, and as soon as it run, i'll let you know mate :smile: 

thx again :+1:

**Comment by drr3d** [comment]
hmmm, i think the easiest way is modifying Telegram-CLI it self, i've done it by creating additional argument(still need more tesstingg :sob:), and (maybe then) parse that argument in pytg(this not done yet :smile:),, still more work to do :sob:

**Comment by luckydonald** [comment]
Argument? You mean a parameter?
Like `telegram-cli --register --phone=+0012345 --code=1234`?
--
It'll usually take a while for @vysheng until he get around to merging patches.

**Comment by luckydonald** [comment]
I believe parsing the `phone number: ` part shouldn't be that difficult, and the code (or call) part too.
I don't expect that string to change anytime soon.

**Comment by luckydonald** [comment]
#52 could benefit from this.

**Comment by drr3d** [comment]
`telegram-cli --register --phone=+0012345 --code=1234` ahhh you right, i forget about the `code` that must we provide, because the code came after we enter the phonenumber :sob: :sob:

**Comment by luckydonald** [comment]
but how to wait for the SMS with the code?

**Comment by luckydonald** [comment]
maybe allow them seperatly?
 `--phone=+001234 --register` and `--phone=+001234 --code=4458`?

**Comment by natsu90** [comment]
Subscribed. This will be awesome.

**Comment by luckydonald** [comment]
@drr3d any progress? Do you have your code modifications here on github?

**Comment by Nanoseb** [comment]
This would be indeed very good. I think Pexpect is the easiest way to do that (moreover the --phone parameter is already working in telegram-cli).

**Comment by Nanoseb** [comment]
Here is a minimal code that works with pexpect: 
```
import pexpect

phone = input('your phone number: ')
child = pexpect.spawn('telegram-cli')

child.expect('phone number:')
child.sendline(phone)

code = input('the verification code: ')
child.expect('code.*')
child.sendline(code)

child.sendline('quit')
```

**Comment by luckydonald** [comment]
I'll have a look into that. Maybe we can Include that.
How do you check whether the cli is registered yet?

I can think of looking in `~/.telegram-cli/...`, but that would be very hacky, and might break...

**Comment by Nanoseb** [comment]
That the only thing I can think of right is looking if .telegram-cli/auth is empty or not, it is not perfect but it is the best we can do without modifying telegram-cli.
The other one would be to see if telegram-cli is asking for a phone number, but it would be even worse (every run you have to wait to see if 'phone number:' is prompt or not).

**Comment by luckydonald** [comment]
Also `auth` might not be present if you are using profiles...

**Comment by Nanoseb** [comment]
Hum, I have never used this, is it working with the current telegram-cli version?
It seems that the -p <profile> parameter is just ignored.

**Comment by Nanoseb** [comment]
Ok, I can't make profile work. 
Anyway it is not a big deal, if you start telegram-cli you have to know the profile name also, so the only thing needed is to put the profile name in the path for this verification.

But I agree with you, it is not very clean...

**Comment by luckydonald** [comment]
You need to write the config file first.
Mine contains:
```javascript
default_profile = "bot2";
bot = {
        config_directory = ".telegram-cli/bot";
        msg_num = true;
        test = true;
};
bot2 = {
        config_directory = ".telegram-cli/bot2";
        msg_num = true;
        test = false    ;
};
luckydonald = {
        config_directory = ".telegram-cli/luckydonald";
        msg_num = true;
        test = false    ;
};
```

**Comment by Gintasz** [comment]
@Nanoseb I'm getting this error with your code, what's wrong? Not a python expert, but need to get this to work

```
Traceback (most recent call last):
  File "telegram_acc_creator.py", line 7, in <module>
    child.sendline(phone)
  File "/Users/gintas/Documents/accpumper/pythonenv/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    s = self._coerce_send_string(s)
  File "/Users/gintas/Documents/accpumper/pythonenv/lib/python2.7/site-packages/pexpect/spawnbase.py", line 140, in _coerce_send_string
    return s.encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
```

**Comment by luckydonald** [comment]
@Gintasz
The traceback says, that `phone` is an integer.
If you used exactly the code [above](#issuecomment-204023527), this would mean `input("...")` returns an integer.

This indicates you use python 2 instead of python 3.

You should use python 3 instead to run the code, as python 2 is a bad choice.

If you _really_ need to stick to python 2, use `raw_input()`, but using python 2 will most certainly give you a hard time when dealing with unicode strings later.

**Comment by bioxakep** [comment]
i use this:
`		telecli = [path_to_cli, '-c',path_to_config,'-p',phone_number,'-q']
		t = time.time()
		
		p = Popen.subprocess(telecli, bufsize=0, stdout=PIPE, stdin=PIPE, stderr=STDOUT, shell=False)
		
		numberRequest = False
		while not numberRequest and time.time() - t < 5:
			if(p.stdout.readline().find("phone")):
				numberRequest = True
		if numberRequest:
			p.stdin.write(number_of_profile)
			print("Number sent")
		else:
			raise Exception('Time out, try run telegram-cli in bash to check error')
		t = time.time()
		
		codeRequest = False
		while not codeRequest and time.time() - t < 5:
			if(p.stdout.readline().find("code")):
				codeRequest = True
		if codeRequest:
			code = input("Enter code:")
			p.stdin.write(int(code))
			print("Code sent")
		else:
			raise Exception('Time out, try run telegram-cli in bash to check error')

		passRequest = False
		while not passRequest and time.time() - t < 5:
			if(p.stdout.readline().find("pass")):
				passRequest = True
		if passRequest:
			passwd = input("Enter password of two-step verification:")
			p.stdin.write(int(passwd))
			print("Password sent")`
