### ISSUE TITLE
Install fails during dependencied installation (DictObject & luckydonald-utils)

### ISSUE THREAD

**Issue by rufinus2** [luckydonald/pytg#78]
### The problem
Install fails during dependencies installation (DictObject & luckydonald-utils)

### Your environment
Python 3.4, pytg latest, Ubuntu 14.04

### Steps to reproduce
running sudo pip install pytg or from source setup.py
```shell
Processing dependencies for pytg==0.4.10
Searching for luckydonald-utils>=0.17
Reading https://pypi.python.org/simple/luckydonald-utils/
Best match: luckydonald-utils 0.43
Downloading https://pypi.python.org/packages/source/l/luckydonald-utils/luckydonald-utils-0.43.tar.gz#md5=d21c423c248ed74ed0a1a83d8d2a4ab0
Processing luckydonald-utils-0.43.tar.gz
Writing /tmp/easy_install-3gup5eno/luckydonald-utils-0.43/setup.cfg
Running luckydonald-utils-0.43/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3gup5eno/luckydonald-utils-0.43/egg-dist-tmp-djhzz5ae
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    install_requires=["DictObject", "luckydonald-utils>=0.17"]
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 96, in do_egg_install
    cmd.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 381, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 597, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 648, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 694, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 620, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 858, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 870, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 50, in run_setup
    lambda: execfile(
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 100, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 52, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "/usr/lib/python3/dist-packages/setuptools/compat.py", line 78, in execfile
    exec(compile(source, fn, 'exec'), globs, locs)
  File "setup.py", line 4, in <module>
    from setuptools import setup  # Always prefer setuptools over distutils
  File "/tmp/easy_install-3gup5eno/luckydonald-utils-0.43/luckydonaldUtils/dependencies/__init__.py", line 3, in <module>
  File "/tmp/easy_install-3gup5eno/luckydonald-utils-0.43/luckydonaldUtils/dependencies/install.py", line 2, in <module>
  File "/tmp/easy_install-3gup5eno/luckydonald-utils-0.43/luckydonaldUtils/dependencies/pip_interface.py", line 12, in <module>
ImportError: No module named 'pip.utils'
```

**Comment by luckydonald** [comment]
I'll have a look.

**Comment by rufinus2** [comment]
Install issue was just solved by removing python 3.4 and installing 3.5.1 with pip 8.1.1.
It looks like issue was cause by old pip version.

**Comment by luckydonald** [comment]
You don't happen to have python 3.4 still around to check if a pip update would solve it there too?

**Comment by fgattoni** [comment]
On debian jessie, (python 3.4.2), I had the same error message. 
Then a `pip3 install --upgrade pip` made it magically disappear.
So I'm guessing pip was too old here, too.

**Comment by luckydonald** [comment]
I am fairly sure this is because of the new [`pytg/dependencies/pip_interface.py`](https://github.com/luckydonald/luckydonald-utils/blob/b8d811afd7f2e3743bc0164c0c5a052feb38fc27/luckydonaldUtils/dependencies/pip_interface.py), which is tying to get around calling pip with it `.main([args])` method, which would removes all logging handlers.
Obviously they changed code internally between pip versions.

**Comment by luckydonald** [comment]
I will probably either remove that code again, or do a version check before

**Comment by researchase** [comment]
I am facing the same issue but I have python 2.7, 
ashwin@ashwin:~/pytg$ sudo python setup.py install
running install
running bdist_egg
running egg_info
creating pytg.egg-info
writing requirements to pytg.egg-info/requires.txt
writing pytg.egg-info/PKG-INFO
writing top-level names to pytg.egg-info/top_level.txt
writing dependency_links to pytg.egg-info/dependency_links.txt
writing manifest file 'pytg.egg-info/SOURCES.txt'
reading manifest file 'pytg.egg-info/SOURCES.txt'
writing manifest file 'pytg.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pytg
copying pytg/argument_types.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/exceptions.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/utils.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/this_py_version.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/test.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/sender.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/receiver.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/__init__.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/fix_msg_array.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/result_parser.py -> build/lib.linux-x86_64-2.7/pytg
copying pytg/fix_plain_output.py -> build/lib.linux-x86_64-2.7/pytg
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/argument_types.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/exceptions.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/utils.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/this_py_version.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/test.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/sender.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/receiver.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/__init__.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/fix_msg_array.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/result_parser.py -> build/bdist.linux-x86_64/egg/pytg
copying build/lib.linux-x86_64-2.7/pytg/fix_plain_output.py -> build/bdist.linux-x86_64/egg/pytg
byte-compiling build/bdist.linux-x86_64/egg/pytg/argument_types.py to argument_types.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/exceptions.py to exceptions.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/this_py_version.py to this_py_version.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/test.py to test.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/sender.py to sender.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/receiver.py to receiver.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/fix_msg_array.py to fix_msg_array.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/result_parser.py to result_parser.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytg/fix_plain_output.py to fix_plain_output.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pytg.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pytg.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pytg.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pytg.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pytg.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/pytg-0.4.10-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pytg-0.4.10-py2.7.egg
Copying pytg-0.4.10-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding pytg 0.4.10 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pytg-0.4.10-py2.7.egg
Processing dependencies for pytg==0.4.10
Searching for luckydonald-utils>=0.17
Reading https://pypi.python.org/simple/luckydonald-utils/
Best match: luckydonald-utils 0.43
Downloading https://pypi.python.org/packages/source/l/luckydonald-utils/luckydonald-utils-0.43.tar.gz#md5=d21c423c248ed74ed0a1a83d8d2a4ab0
Processing luckydonald-utils-0.43.tar.gz
Writing /tmp/easy_install-IFoaDH/luckydonald-utils-0.43/setup.cfg
Running luckydonald-utils-0.43/setup.py -q bdist_egg --dist-dir /tmp/easy_install-IFoaDH/luckydonald-utils-0.43/egg-dist-tmp-2sJqcX
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    install_requires=["DictObject", "luckydonald-utils>=0.17"]
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 391, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 621, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 672, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 720, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 825, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1070, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1082, in obtain
    return installer(requirement)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 640, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 670, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 853, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1081, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1067, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 246, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-IFoaDH/luckydonald-utils-0.43/setup.py", line 4, in <module>
    from setuptools import setup  # Always prefer setuptools over distutils
  File "/tmp/easy_install-IFoaDH/luckydonald-utils-0.43/luckydonaldUtils/dependencies/__init__.py", line 3, in <module>
  File "/tmp/easy_install-IFoaDH/luckydonald-utils-0.43/luckydonaldUtils/dependencies/install.py", line 2, in <module>
  File "/tmp/easy_install-IFoaDH/luckydonald-utils-0.43/luckydonaldUtils/dependencies/pip_interface.py", line 12, in <module>
ImportError: No module named utils
ashwin@ashwin:~/pytg$ sudo pip install DictObject
Downloading/unpacking DictObject
  Downloading DictObject-0.1.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/DictObject/setup.py) egg_info for package DictObject
    
Downloading/unpacking luckydonald-utils (from DictObject)
  Downloading luckydonald-utils-0.43.tar.gz
  Running setup.py (path:/tmp/pip_build_root/luckydonald-utils/setup.py) egg_info for package luckydonald-utils
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/luckydonald-utils/setup.py", line 4, in <module>
        from luckydonaldUtils.dependencies import find_submodules
      File "/tmp/pip_build_root/luckydonald-utils/luckydonaldUtils/dependencies/__init__.py", line 3, in <module>
        from .install import find_packages, import_or_install, import_only, find_submodules
      File "/tmp/pip_build_root/luckydonald-utils/luckydonaldUtils/dependencies/install.py", line 2, in <module>
        from .pip_interface import pip_install
      File "/tmp/pip_build_root/luckydonald-utils/luckydonaldUtils/dependencies/pip_interface.py", line 12, in <module>
        from pip.utils import get_prog
    ImportError: No module named utils
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/luckydonald-utils/setup.py", line 4, in <module>

    from luckydonaldUtils.dependencies import find_submodules

  File "/tmp/pip_build_root/luckydonald-utils/luckydonaldUtils/dependencies/__init__.py", line 3, in <module>

    from .install import find_packages, import_or_install, import_only, find_submodules

  File "/tmp/pip_build_root/luckydonald-utils/luckydonaldUtils/dependencies/install.py", line 2, in <module>

    from .pip_interface import pip_install

  File "/tmp/pip_build_root/luckydonald-utils/luckydonaldUtils/dependencies/pip_interface.py", line 12, in <module>

    from pip.utils import get_prog

ImportError: No module named utils

**Comment by luckydonald** [comment]
Please install `luckydonald-utils` [`v0.41`](https://github.com/luckydonald/luckydonald-utils/releases/tag/v0.42)
E.g.
```shell
pip install luckydonald-utils==0.41
```

**Comment by luckydonald** [comment]
I will investigate.

**Comment by luckydonald** [comment]
Yep.

**Comment by luckydonald** [comment]
That should address that.
