### ISSUE TITLE
send message to dialog list

### ISSUE THREAD

**Issue by efazati** [luckydonald/pytg#85]
### The problem
I want send msg to dialog list but i receive error. change peer id type and another things but not work again
what can i do

```

import pytg
from pytg import argument_types as args


def main():
    tg = pytg.Telegram(telegram="/home/argus/10days/telefollow/tg/bin/telegram-cli", pubkey_file="/home/argus/.ssh/id_rsa.pub")
    result = tg.sender.dialog_list()
    peer_id = args.Peer(str(result[0]['peer_id']))
    string = args.UnicodeString('hiiiii')
    tg.sender.send_msg(peer_id, string)
```

# Error
```
Traceback (most recent call last):
  File "sample.py", line 21, in <module>
    main()
  File "sample.py", line 18, in main
    tg.sender.send_msg(peer_id, string)
  File "/home/argus/10days/telefollow/env/local/lib/python2.7/site-packages/pytg/sender.py", line 632, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/home/argus/10days/telefollow/env/local/lib/python2.7/site-packages/pytg/sender.py", line 357, in execute_function
    raise e
pytg.exceptions.FailException: Error 38: u'can not parse arg #1' (command u'[disable_preview] msg <1051030938> <hiiiii>\n')

```
i use str but not work too

### Your environment
py: 2.7 and ubuntu

**Comment by Nanoseb** [comment]
You need to specify the `print_name` instead of the `peer_id`.
Moreover it seems that your pubkey file is not the right one, it has to be the one called `server.pub` from the telegram-cli folder (it is the pubkey of telegram servers not from your computer)

**Comment by luckydonald** [comment]
You don't need `args.*`.

Your line should *probably* only be: <sup> (Note: untested)</sup>
```python
tg.sender.send_msg(str(result[0]['print_name']), 'hiiiii')
```
