### ISSUE TITLE
export_chat_link result is a link

### ISSUE THREAD

**Issue by firewut** [luckydonald/pytg#90]
### The problem
[group_chat](https://github.com/luckydonald/pytg/blob/master/DOCUMENTATION_manual.md#group-chat-related) related `export_chat_link` method returns a `{"result":"https://telegram.me/joinchat/my-link"}`. Method raises 
```
pytg.exceptions.IllegalResponseException: Found: {'result': 'https://telegram.me/joinchat/AhQ6ZggVDJKeLlrug9jxAA'}
```

### Your environment
python: 3.4

pytg: v0.4.10

OS: Dockerized ubuntu

tg: Telegram-cli version 1.4.1 (uses tgl version 2.1.0)

### Steps to reproduce
Detailed steps to reproduce the issue.
```
sender = Sender("127.0.0.1", 4458)
sender.create_group_chat(topic, user)
link=sender.export_chat_link(topic)
```

### Expected behaviour

`link` should equal 'https://telegram.me/joinchat/AhQ6ZggVDJKeLlrug9jxAA'

### Actual behaviour

But exception is being raised:

```
pytg.exceptions.IllegalResponseException: Found: {'result': 'https://telegram.me/joinchat/AhQ6ZggVDJKeLlrug9jxAA'}
```

### Full debug output

```python
DEBUG:pytg.sender:Sending command >[disable_preview] contact_list 
<
DEBUG:pytg.sender:Socket Connected.
DEBUG:pytg.sender:All Sent.
DEBUG:pytg.sender:Parsing dialog_list: Argument 100 - [limit] (needed)
DEBUG:pytg.sender:Skipping missing optional parameter #1 [offset] (type NonNegativeNumber) in function dialog_list.
DEBUG:pytg.sender:Sending command >[disable_preview] dialog_list 100
<
DEBUG:pytg.sender:Socket Connected.
DEBUG:pytg.sender:All Sent.
DEBUG:pytg.sender:Parsing chat_info: Argument DO_NOT_DELETE_IT - <chat> (needed)
DEBUG:pytg.sender:Sending command >[disable_preview] chat_info DO_NOT_DELETE_IT
<
DEBUG:pytg.sender:Socket Connected.
DEBUG:pytg.sender:All Sent.
DEBUG:pytg.sender:Parsing export_chat_link: Argument DO_NOT_DELETE_IT - <chat> (needed)
DEBUG:pytg.sender:Sending command >[disable_preview] export_chat_link DO_NOT_DELETE_IT
<
DEBUG:pytg.sender:Socket Connected.
DEBUG:pytg.sender:All Sent.
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    print(create_group_chat("DO_NOT_DELETE_IT", "photo", "Chat description", "@combot"))
  File "main.py", line 25, in create_group_chat
    res3 = sender.export_chat_link(topic)
  File "/usr/local/lib/python3.4/dist-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pytg/sender.py", line 351, in execute_function
    return result_parser(message)
  File "/usr/local/lib/python3.4/dist-packages/pytg/result_parser.py", line 56, in success_fail
    raise IllegalResponseException("Found: {}".format(json))
pytg.exceptions.IllegalResponseException: Found: {'result': 'https://telegram.me/joinchat/AhQ6ZggVDJKeLlrug9jxAA'}
INFO:pytg.sender:Quit Sending. Not allowing sending anymore.
WARNING:pytg.sender:Terminating currently sending request.
INFO:pytg.sender:Currently not Sending.
```

**Comment by luckydonald** [comment]
There would be needed a different parser function.
Have a look into [`success_fail` (pytg/result_parser.py:37)](https://github.com/luckydonald/pytg/blob/bfa1e16c9b86c14e7b2fa44ead8514ed857b40fb/pytg/result_parser.py#L37).
You could write your own `chat_link` function to accomplish that.
And modify [pytg/sender.py:123](https://github.com/luckydonald/pytg/blob/bfa1e16c9b86c14e7b2fa44ead8514ed857b40fb/pytg/sender.py#L123) like the following.
```diff
- functions["export_chat_link"]     = ("export_chat_link", [args.Chat("chat")], res.success_fail, None, "Prints chat link that can be used to join to chat")
+ functions["export_chat_link"]     = ("export_chat_link", [args.Chat("chat")], res.chat_link,    None, "Prints chat link that can be used to join to chat")
```
I have not much time to spare, So I can't implement it by myself, but would appreciate to merge a pull request.
