### ISSUE TITLE
AttributeError: 'int' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by a3dho3yn** [luckydonald/pytg#91]
### The problem
While using the receiver, upon receiving a message this error occurs:
```
Exception in thread Receiver (pytg):
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pytg/receiver.py", line 149, in _receiver
    self._add_message(text)
  File "/usr/local/lib/python3.4/dist-packages/pytg/receiver.py", line 184, in _add_message
    message = fix_message(message)
  File "/usr/local/lib/python3.4/dist-packages/pytg/fix_msg_array.py", line 24, in fix_message
    message["sender"] = fix_peer(message["from"])
  File "/usr/local/lib/python3.4/dist-packages/pytg/fix_msg_array.py", line 57, in fix_peer
    elif "id" in peer and peer["id"].startswith("$"):
AttributeError: 'int' object has no attribute 'startswith'
```

### Your environment
Debian 8.4
Python 3.4.2
pytg 0.4.8

### Steps to reproduce
Run [bot dump](https://github.com/luckydonald/pytg/blob/master/examples/bot_dump.py) example with python3 

### Expected behaviour
Print message

### Actual behaviour
Raising error!

**Comment by a3dho3yn** [comment]
I think you should use str()
`peer["id"].startswith("$")`
should be
`str(peer["id"]).startswith("$")`

**Comment by luckydonald** [comment]
Looks right.
If you like you can edit that in yourself and create a pull request. 
I'd be happy to merge that. 
It probably will take some time to look into it, as I have no cli set up right now.

**Comment by luckydonald** [comment]
I would be interested in the **json output** of the CLI and the **start parameters** the CLI was started with.

Both should get printed in the [**debug log**](https://github.com/luckydonald/pytg#in-case-of-errors).

**Comment by a3dho3yn** [comment]
Telegram-cli version 1.3.3
`bin/telegram-cli -k tg-server.pub --json -P 9999`
