### ISSUE TITLE
KeyError: 'peer_id'

### ISSUE THREAD

**Issue by a3dho3yn** [luckydonald/pytg#92]
### The problem
While using receiver, upon receiving a message, this exception raises:
```
Exception in thread Receiver (pytg):
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pytg/receiver.py", line 149, in _receiver
    self._add_message(text)
  File "/usr/local/lib/python3.4/dist-packages/pytg/receiver.py", line 184, in _add_message
    message = fix_message(message)
  File "/usr/local/lib/python3.4/dist-packages/pytg/fix_msg_array.py", line 24, in fix_message
    message["sender"] = fix_peer(message["from"])
  File "/usr/local/lib/python3.4/dist-packages/pytg/fix_msg_array.py", line 63, in fix_peer
    peer["cmd"] = u("{type}#{peer_id}").format(type=peer["type"], peer_id=peer["peer_id"])
KeyError: 'peer_id'
```

### Your environment
Debia 8.4
Python 3.4.2
pytg 0.4.8

### Steps to reproduce
Run bot dump example

### Expected behaviour
Print received message

### Actual behaviour
Raises error!

**Comment by a3dho3yn** [comment]
Key should be "id" instead of "peer_id" (line 63 and 65 of fix_msg_array.py)

**Comment by luckydonald** [comment]
Current commit in Master is [`bfa1e1`](https://github.com/luckydonald/pytg/tree/bfa1e16c9b86c14e7b2fa44ead8514ed857b40fb).

**Comment by luckydonald** [comment]
Can you again post the **json output** of the CLI and the **start parameters** the CLI was started with, as well as the **CLI version** (is it the most recent? Else please execute `git log -1` in the directory of the cli)

Both the output and the parameters should get printed in the [**debug log**](https://github.com/luckydonald/pytg#in-case-of-errors).

**Comment by a3dho3yn** [comment]
Telegram-cli version 1.3.3
`bin/telegram-cli -k tg-server.pub --json -P 9999`

**Comment by a3dho3yn** [comment]
This error raised after fixing #91 (by wrapping peer["id"] with str())

**Comment by luckydonald** [comment]
Could you please post the json output of a message the cli outputs? You may of course replace sensible information like phone numbers etc. I am mainly interested in the attribute names.

Could you after that do the same procedure after you append `--permanent-peer-ids --permanent-peer-ids` to the cli arguments?

Because I believe the structure there might be different.

**Comment by luckydonald** [comment]
FYI: pytg usually starts the CLI with [this arguments](https://github.com/luckydonald/pytg/blob/2ceb4717bd1621dc022ceb923a07b14e2f720c3d/pytg/__init__.py#L76-L80).

**Comment by sae13** [comment]
how i can get receiver peer_id? i wanna if this msg is in a special group
