### ISSUE TITLE
Error in function create_group_chat: 2 paramters expected, but 3 were given

### ISSUE THREAD

**Issue by mefuckin** [luckydonald/pytg#97]
### The problem
Cannot call `create_group_chat()` with more than 2 arguments.

### Your environment
Python 3.5.2
pytg 0.4.10

### Steps to reproduce
Run this code:
```
from pytg import Telegram
tg = Telegram(telegram='tg/bin/telegram-cli', pubkey_file='tg/server.pub')
tg.sender.create_group_chat('test',  'user#12345', 'user#78910')
```

### Expected behaviour
Send `create_group_chat test user#12345 user#78910` to telegram-cli.

### Actual behaviour
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pytg/sender.py", line 274, in execute_function
    command_name, new_args = self._validate_input(function_name, arguments)
  File "/usr/local/lib/python3.5/dist-packages/pytg/sender.py", line 379, in _validate_input
    function_name=function_name, expected_number=len(arguments_types), given_number=len(arguments))
ValueError: Error in function create_group_chat: 2 paramters expected, but 3 were given.
```

**Comment by luckydonald** [comment]
Interesting. 
```python
args.User("user", multible=True)]
```
In [pytg/sender.py:121](https://github.com/luckydonald/pytg/blob/2ceb4717bd1621dc022ceb923a07b14e2f720c3d/pytg/sender.py#L121) is at least correctly.

**Comment by luckydonald** [comment]
It seems, the `multible=True` part is not covered in that function.
